spring:
  application:
    name: assistant

  datasource:
    url: jdbc:postgresql://localhost:5432/assistant
    username: assistant
    password: assistant

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.sql

  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: qwen3:4b
      embedding:
        model: nomic-embed-text

    vectorstore:
      pgvector:
        initialize-schema: false
        dimensions: 768
        distance-type: COSINE_DISTANCE
        index-type: HNSW
